### ISSUE TITLE
SASS

### ISSUE THREAD

**Issue by sikanhe** [thereactivestack/kickstart#10]
I tried to rebuild node-sass with the instructions in fix-sass.sh. It rebuilt, but now it has a different error:

W20150926-23:02:33.033(-4)? (STDERR) dyld: lazy symbol binding failed: Symbol not found: _node_module_register
W20150926-23:02:33.034(-4)? (STDERR)   Referenced from: /Users/sikanhe/desktop/kickstart/node_modules/node-sass/vendor/darwin-x64-11/binding.node
W20150926-23:02:33.034(-4)? (STDERR)   Expected in: flat namespace
W20150926-23:02:33.034(-4)? (STDERR) 
W20150926-23:02:33.034(-4)? (STDERR) dyld: Symbol not found: _node_module_register
W20150926-23:02:33.034(-4)? (STDERR)   Referenced from: /Users/sikanhe/desktop/kickstart/node_modules/node-sass/vendor/darwin-x64-11/binding.node
W20150926-23:02:33.034(-4)? (STDERR)   Expected in: flat namespace
W20150926-23:02:33.034(-4)? (STDERR) 
=> Exited from signal: SIGTRAP

**Comment by sikanhe** [comment]
my node version is v4.1.0 and npm is v2.14.3 i dont know if this has anything to do with it

**Comment by eXon** [comment]
That's weird. Are you running run-dev.sh or prod-dev.sh?

**Comment by eXon** [comment]
You might want to delete your node_modules folder and start over. It seems it is a random problem people are having that can be fixed that way.

**Comment by eXon** [comment]
I've updated the fix-saas.sh script to force the correct Node.js version for Meteor. Seems to work for me with 4.1. Does it work for you?

**Comment by sikanhe** [comment]
I tried it again with the new fix-sass.sh, even through i set it to use darwin-x64-11 it installed it as x64-46....i think it has something to do with the new OS X version not sure..

But I have been using postcss instead of sass now, much more modular which I like. 

And thank you for making this project, I wouldnt have been able to know how to set up hot reload with meteor correctly myself. Keep up the good work!

**Comment by eXon** [comment]
I really want this script to work correctly. Was it generating node_modules/node-sass/vendor/darwin-x64-11? If not there is something wrong with the script. If yes then, ... I don't know.

**Comment by sikanhe** [comment]
No it's generating x64-46 even though i told it to use x64-11

**Comment by eXon** [comment]
Are you using the last fix-sass.sh script?

Can you also make sure that SASS_BINARY_NAME is not defined?
`export SASS_BINARY_NAME=`

The first script was using it.

**Comment by etamity** [comment]
Mine is darwin-x64-14, but it always loading from darwin-x64-11 
I have used the fix-sass.sh script , even i set SASS_BINARY_NAME  to darwin-x64-11,  it will rebuild in 
darwin-x64-14
gyp info ok 
Installed in ` /Users/joey/Documents/joeycodes/MacDevelop/joey/music/FireEngine/node_modules/node-sass/vendor/darwin-x64-14/binding.node `
===========
Error: The `libsass` binding was not found in /Users/joey/Documents/joeycodes/MacDevelop/joey/music/fireengine/node_modules/node-sass/vendor/darwin-x64-11/binding.node
W20150929-12:05:24.646(1)? (STDERR) This usually happens because your node version has changed.
W20150929-12:05:24.646(1)? (STDERR) Run `npm rebuild node-sass` to build the binding for your current node version.

**Comment by eXon** [comment]
That's weird. You set `darwin-x64-11` in fix-sass.sh and executed the script and got not file in the node_modules/node-sass/vendor/darwin-x64-11?

Might be a problem with Mac only. I'll try to get one and see how I can fix that.

**Comment by eXon** [comment]
It should work now, I've tested it with darwin-x64-11

**Comment by coniel** [comment]
Getting this error:
```
ERROR in The `libsass` binding was not found in C:\Users\Administrator\edfora\lms\.meteor\local\webpack-npm\node_modules\node-sass\vendor\win32-ia32-11\binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
 @ ../core/ui/client/styles/grid.scss 4:14-274 13:2-17:4 14:20-280
```

Tried running the fix-sass.bat script (set sass binary name to `win32-ia32-11`), but still getting the error. Here is what the script outputted: https://gist.github.com/coniel/b6e777a82e15ac390fa5 (doesn't seem to be any errors).

**Comment by coniel** [comment]
I finally discovered that the fix-sass wasn't actually running because I didn't have C++ VSBuild.exe installed on my pc. I did install it but if i try to run fix-sass.bat, I still get the following errors:

```
...
Build started 12/3/2015 2:48:34 AM.
Project "C:\Users\Administrator\edfora\lms\node_modules\node-sass\build\binding
.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
libsass:
  C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\IDE\..\..\vc\vcpacka
  ges\vcbuild.exe C:\Users\Administrator\edfora\lms\node_modules\node-sass\buil
  d\src\libsass.vcproj "Release|x64"
  Error: project file 'C:\Users\Administrator\edfora\lms\node_modules\node-sass
  \build\src\libsass.vcproj' was not found or not a valid project file.
  The project consists entirely of configurations that require support for plat
  forms which are not installed on this machine. The project cannot be loaded.
MSBUILD : error MSB6006: "VCBuild.exe" exited with code -1. [C:\Users\Administr
ator\edfora\lms\node_modules\node-sass\build\binding.sln]
Done Building Project "C:\Users\Administrator\edfora\lms\node_modules\node-sass
\build\binding.sln" (default targets) -- FAILED.
Build FAILED.
"C:\Users\Administrator\edfora\lms\node_modules\node-sass\build\binding.sln" (d
efault target) (1) ->
(libsass target) ->
  MSBUILD : error MSB6006: "VCBuild.exe" exited with code -1. [C:\Users\Adminis
trator\edfora\lms\node_modules\node-sass\build\binding.sln]
    0 Warning(s)
    1 Error(s)
Time Elapsed 00:00:00.86
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\edfora\lms\.meteor\local\webpack-npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\edfora\\lms\\.meteor\\local\\webpack-npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library=" "--target=v0.10.40"
gyp ERR! cwd C:\Users\Administrator\edfora\lms\node_modules\node-sass
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v3.2.0
gyp ERR! not ok
Build failed
```
